name: focal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Every Wednesday at 11:03 UTC.
    - cron: '3 11 * * 3'

jobs:
  focal-build-swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: build swiftlint
      run: ./ci/build-swiftlint.sh
    - uses: actions/upload-artifact@v2
      with:
        name: swiftlint
        path: swiftlint
  focal-run-swiftlint:
    needs: focal-build-swiftlint
    runs-on: ubuntu-latest
    container: swift:5.6.2-focal
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: swiftlint
    - run: chmod +x ./swiftlint
    - run: ./swiftlint
